// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvKYvMHA6pH0fupiL9gGE0cL55BdptZc',
    appId: '1:546995305655:web:9bdb4dbc57c63c9ab46132',
    messagingSenderId: '546995305655',
    projectId: 'myfirstfirebaseproject-c35dd',
    authDomain: 'myfirstfirebaseproject-c35dd.firebaseapp.com',
    storageBucket: 'myfirstfirebaseproject-c35dd.firebasestorage.app',
    measurementId: 'G-RXY3S89PQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHzUfEwvtNtP_0jBV2TyGHm-v7v7ajQYw',
    appId: '1:546995305655:android:c6747d1ddac3ad81b46132',
    messagingSenderId: '546995305655',
    projectId: 'myfirstfirebaseproject-c35dd',
    storageBucket: 'myfirstfirebaseproject-c35dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ97g_hWL2-yO49MzaaTuZJO0AlVLzOBU',
    appId: '1:546995305655:ios:853bdf4b5dddcf73b46132',
    messagingSenderId: '546995305655',
    projectId: 'myfirstfirebaseproject-c35dd',
    storageBucket: 'myfirstfirebaseproject-c35dd.firebasestorage.app',
    iosBundleId: 'com.example.baas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ97g_hWL2-yO49MzaaTuZJO0AlVLzOBU',
    appId: '1:546995305655:ios:853bdf4b5dddcf73b46132',
    messagingSenderId: '546995305655',
    projectId: 'myfirstfirebaseproject-c35dd',
    storageBucket: 'myfirstfirebaseproject-c35dd.firebasestorage.app',
    iosBundleId: 'com.example.baas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRvKYvMHA6pH0fupiL9gGE0cL55BdptZc',
    appId: '1:546995305655:web:50ea81043135a681b46132',
    messagingSenderId: '546995305655',
    projectId: 'myfirstfirebaseproject-c35dd',
    authDomain: 'myfirstfirebaseproject-c35dd.firebaseapp.com',
    storageBucket: 'myfirstfirebaseproject-c35dd.firebasestorage.app',
    measurementId: 'G-RPXPKT6P26',
  );
}
